// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


function throttle(type_, name, target) {
  var running = [false];
  var func = function () {
    while(!running[0]) {
      running[0] = true;
      requestAnimationFrame((function () {
              target.dispatchEvent(new Event(name));
              running[0] = false;
              return /* () */0;
            }));
    };
    return /* () */0;
  };
  target.addEventListener(type_, func);
  return /* () */0;
}

throttle("resize", "optimizedResize", window);

window.addEventListener("optimizedResize", (function () {
        var width = window.outerWidth;
        var height = window.outerHeight;
        if (height !== width) {
          window.resizeTo(width, width);
          return /* () */0;
        } else {
          return 0;
        }
      }));

/*  Not a pure module */
